### ISSUE TITLE
running on Windows 10 breaks incoming voice chat audio

### ISSUE THREAD

**Issue by AlpacaSundae** [arkrow/PyMusicLooper#21]
**Describe the bug**
When importing this library on windows 10, incoming voice chat playback breaks.
It happens on both Discord and Steam, after running, the microphone from the Windows 10 machine still transmits audio to the other participants, but it does not receive anyone elses audio until leaving/reconnecting [it doesn't matter who reconnects]
 
**Debugging Information**
n/a as the script itself appears to function normally
I've run this myself on WIndows 11 and linux with no issues, just on my friends Windows 10 machine this issue occurs

**Expected behavior**
All previous audio streams should be unaffected by launching the script

**Environment Information (please complete the following information):**
- OS: Windows 10
- PyMusicLooper version being used: 3.1.0
- Is FFmpeg installed and working?: Yes

**Comment by arkrow** [comment]
It seems this issue occurs on Windows if exclusive mode is enabled on the default sound device, specifically when the `sounddevice` library is initialized. I'll open an issue in the affected library's issue tracker, and hopefully, I can then update to their fix in a later release.

In the meantime (if this issue is a regular/annoying occurrence), exclusive mode can be disabled in the default sound device as a temporary workaround.

**Comment by arkrow** [comment]
This issue has been fixed upstream in sounddevice (the related, now closed, issue: https://github.com/spatialaudio/python-sounddevice/issues/496; many thanks to the efforts of sounddevice's maintainer). The project dependencies have been updated and this issue should be fixed in PyMusicLooper as of the v3.4.2 release.
