### ISSUE TITLE
Loop file size

### ISSUE THREAD

**Issue by Daviid-P** [arkrow/PyMusicLooper#31]
Is it normal for the loop part to be almost 10 times bigger than the main opus file?

I was trying to loop these 3 videos to have a shorter smaller file instead of a 70MB 1 hour file.

- OcR2mvq_REk
- Qa6sQrj8taY
- irAAKLSGYec

However `my heart has lived a thousand lifetimes (ambient music, dark academia) [OcR2mvq_REk].opus` is 70MB while 

- `my heart has lived a thousand lifetimes (ambient music, dark academia) [OcR2mvq_REk].opus-intro.wav` is 65MB
- `my heart has lived a thousand lifetimes (ambient music, dark academia) [OcR2mvq_REk].opus-loop.wav` is 518MB
- `my heart has lived a thousand lifetimes (ambient music, dark academia) [OcR2mvq_REk].opus-outro.wav` is 93MB

Am I doing something wrong?

Also I know at least one of the video has 2 songs inside (fades out fades in), will the script pick up those smaller loops or will it try to find a loop for the whole file? Should I split the file first?

**Comment by arkrow** [comment]
> Is it normal for the loop part to be almost 10 times bigger than the main opus file?

It's normal, since, by default, PyMusicLooper outputs in the ubiquitous WAV format (which is lossless and uncompressed) to avoid information loss from lossy encodes like MP3/OPUS, especially since each encoder has its own quality parameters and supporting those is out of scope for this tool. That said, there is some basic support for output file format, like FLAC, MP3 and OGG, (see the `--format` option here: https://github.com/arkrow/PyMusicLooper/blob/master/CLI_README.md#pymusiclooper-split-audio), but users are encouraged to encode the files using an external tool like `ffmpeg` instead for better control over desired quality/size. FLAC might be a good middle-ground as its lossless but compressed.


> Also I know at least one of the video has 2 songs inside (fades out fades in), will the script pick up those smaller loops or will it try to find a loop for the whole file? Should I split the file first?

It tries to find a single main loop to use, but you can either cut the track as you said to roughly the desired sections (since you're saying there are two songs inside), or, you can use the created `-loop` section as input for analysis recursively (this works surprisingly well, depending on the track), so you can get desired sub-loop sections from a main loop this way.

**Comment by Daviid-P** [comment]
I understand that WAV is uncompressed but being the input an already compressed OPUS where does the extra data come from?

Can you decompress an OPUS file?

**Comment by arkrow** [comment]
It's not that the WAV format generates new information (it doesn't), but rather, the way the data is represented. To use an analogy, it'd be as if a compressed zip file was the input, and raw uncompressed data as the output; or a medium-quality JPG as the input and a raw bitmap image as the output. In both cases, it's lossy or lossless compressed data (with the codec algorithm encoding *(i.e. representing)* the data in a way that uses minimal space) to the raw decoded uncompressed data.

WAV uses 16 bits to represent each audio sample. Depending on the original file's sample rate--assuming the common 44.1kHz--that would be 11.5 MB per minute of audio. If your loop section is 518MB, if it uses a 44.1kHz sampling rate, then that's around ~47 minutes of raw audio data.

For reference, lossy audio codecs (like MP3/AAC/OPUS) usually discard some of the original audio data to minimize the storage space used. Information lost during lossy encodes cannot be recovered, which is why quality can degrade quickly with repeated lossy re-encodes. You are free to use a different format using the `--format` option. WAV is used by default to avoid information loss from repeated lossy re-encodes.
