### ISSUE TITLE
Support `LOOPLENGTH` tag

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [arkrow/PyMusicLooper#45]
**Is your feature request related to a problem? Please describe.**

PyMusicLooper's tagging support currently only supports specifying the loop end position in absolute terms. Some game engines (e.g. RPG Maker) instead require the loop end position to be specified relative to the loop start position (via the `LOOPLENGTH` tag).

**Describe the solution you'd like**

Make PyMusicLooper check whether the loop end position tag name has `LEN` as a (case-insensitive) substring, and if so, make it a relative length rather than an absolute position.

**Describe alternatives you've considered (if relevant)**

A separate command-line boolean flag could be used, but this seems like it would be less user-friendly.

**Additional context**

I would be happy to submit a PR if you would be amenable to accepting one.

**Comment by arkrow** [comment]
Hello @Splendide-Imaginarius, thanks for the detailed request. With regards to your comments:

> Make PyMusicLooper check whether the loop end position tag name has `LEN` as a (case-insensitive) substring, and if so, make it a relative length rather than an absolute position.

I'd also `OFFSET` alongside `LEN` as another potential trigger to be relative. 

> A separate command-line boolean flag could be used, but this seems like it would be less user-friendly.

I suppose a good middle-ground would be to add an optional boolean flag to override the automatic behavior like `--offset/--no-offset`

Overall it should be a simple change in the tag export function, alongside a new override CLI flag for `tag` that is passed through to the function through the export handler. It'll be on the backlog for a bit, scheduled for the next release, since I'm working on several features/improvements, but please feel free to open a PR if you'd like (contributions are always welcome!)
